name: Publish Webex design customize
on:
  workflow_dispatch:
    inputs:
      base_url:
        required: true
        type: string

jobs:
  jobBuild:
    name: Publish Webex design customize
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build angular
      uses: ArthusLiang/angular-deploy-gh-pages-actions@master
      with:
        github_access_token: ${{ secrets.ACTION_TOKEN }} 
        # build_configuration: staging # The build environment for the app. please look configurations in your angular.json
        base_href: ${{ inputs.base_url }}   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: gh-pages # The branch the action should deploy to.
        deploy_folder: ./ #target folder
        angular_dist_build_folder: dist/momentum # The folder where your project

