name: Publish Webex design customize
on:
  workflow_dispatch:
    inputs:
      cname:
        required: true
        type: string
      genereateCNAME:
        required: true
        default: false
        type: boolean

jobs:
  jobBuild:
    name: Publish Webex design
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@master
      with:
          fetch-depth: 2
    - name: Install Package
      run: npm install
    - name: ng build
      run: npm run build-static repo='${{ github.repository }}' cname='${{ inputs.cname }}' genereateCNAME='$${{ inputs.genereateCNAME }}'
    - name: Push git subdirectory as branch
      uses: s0/git-publish-subdir-action@v2.5.1
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }} 
        SKIP_EMPTY_COMMITS: true
        MESSAGE: "[skip ci](build static site):{msg}"